swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: localhost:3000
basePath: /
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: |
      Authentication tupes for bearer header

paths:
  /gets-Dokter:
    get:
      summary: Returns a list of posts-dokter.
      description: |
        Optional extended description in Markdown.
      tags:
        - "posts-dokter"
      parameters:
        - name: search
          in: query
          type: string
          description: parameter for search the gets-dokter
      produces:
        - application/json
      responses:
        200:
          description: OK
  /posts-dokter:
    post:
      summary: Create new posts-dokter.
      description: Create new post-dokter and return the created data
      tags:
        - "posts-dokter"
      security:
        - Bearer: []
      parameters:
        - name: create post
          in: body
          required: true
          description: Create post body request
          schema:
            type: object
            properties:
              nomor_registrasi:
                type: string
              nama_dokter:
                type: string
              profesi:
                type: string
              jenis_kelamin:
                type: string
              email:
                type: string
              nomor_telepon:
                type: string
              alamat:
                type: string
              jadwal_praktek:
                type: array
      produces:
        - application/json
      responses:
        200:
          description: OK

  /getsone-dokter/{id}:
    get:
      summary: Returns one of post-dokter.
      description: |
        Returns one post with it's details and authors
      tags:
        - "posts-dokter"
      parameters:
        - in: path
          name: id
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK

  /edit-dokter/{id}:
    put:
      summary: Update one of post
      description: |
        Update one post
      tags:
        - "posts-dokter"
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - name: Update post
          in: body
          required: true
          description: Update post body request
          schema:
            type: object
            properties:
              nomor_registrasi:
                type: string
              nama_dokter:
                type: string
              profesi:
                type: string
              jenis_kelamin:
                type: string
              email:
                type: string
              nomor_telepon:
                type: string
              alamat:
                type: string
              jadwal_praktek:
                type: array
      produces:
        - application/json
      responses:
        200:
          description: OK

  /delete-dokter/{id}:
    delete:
      summary: Delete one of post-dokter.
      description: |
        Delete one post with it's details authors
      tags:
        - "posts-dokter"
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK

  /gets-Pasien:
    get:
      summary: Returns a list of post-pasien.
      description: |
        Optional extended description in Markdown.
      tags:
        - "posts-pasien"
      parameters:
        - name: search
          in: query
          type: string
          description: parameter for search the posts-pasien.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /posts-Pasien:
    post:
      summary: Create new post-pasien.
      description: Create new post-pasien and return the created data.
      tags:
        - "posts-pasien"
      security:
        - Bearer: []
      parameters:
        - name: create post
          in: body
          required: true
          description: Createpost body request
          schema:
            type: object
            properties:
              nama_pasien:
                type: string
              umur:
                type: number
              jenis_kelamin:
                type: string
              berat_badan:
                type: number
              tinggi_badan:
                type: number
              alamat:
                type: string
              nomor_telepon:
                type: string
              asuransi:
                type: boolean
      produces:
        - application/json
      responses:
        200:
          description: OK

  /getsone-Pasien/{id}:
    get:
      summary: Returns one of getone-pasien.
      description: |
        Returns one post with it's details and authors
      tags:
        - "posts-pasien"
      parameters:
        - in: path
          name: id
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK

  /edit-Pasien/{id}:
    put:
      summary: Update one of post-pasien
      description: |
        Update one post
      tags:
        - "posts-pasien"
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - name: Update post
          in: body
          required: true
          description: Update post body request
          schema:
            type: object
            properties:
              nama_pasien:
                type: string
              umur:
                type: number
              jenis_kelamin:
                type: string
              berat_badan:
                type: number
              tinggi_badan:
                type: number
              alamat:
                type: string
              nomor_telepon:
                type: string
              asuransi:
                type: boolean
      produces:
        - application/json
      responses:
        200:
          description: OK

  /delete-Pasien/{id}:
    delete:
      summary: Delete one of post-pasien.
      description: |
        Delete one post with it's details authors
      tags:
        - "posts-pasien"
      security:
        - Bearer: []
      parameters:
        - in: path
          name: id
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: OK

  /postcheck-Bmi:
    post:
      summary: Create new posts-checkBmi.
      description: Create new post-dokter and return the created data
      tags:
        - "posts-checkBmi"
      security:
        - Bearer: []
      parameters:
        - name: create post
          in: body
          required: true
          description: Create post body request
          schema:
            type: object
            properties:
              nama_pasien:
                type: string
              umur:
                type: number
              jenis_kelamin:
                type: string
              berat_badan:
                type: number
              tinggi_badan:
                type: number

      produces:
        - application/json
      responses:
        200:
          description: OK
